# Generated by Django 2.0.6 on 2020-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='aa', upload_to='pics'),
            preserve_default=False,
        ),
    ]
