# Generated by Django 2.0.6 on 2020-01-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_employee_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
